name: Build Flutter Windows Installer
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Clean project
        run: flutter clean

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Create installer folder
        run: mkdir installer

      - name: Build Installer
        run: iscc windows/installer.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: XMLParserInstaller
          path: windows/installer/XMLParserSetup.exe